ALTER TABLE messages ADD COLUMN input_tokens INTEGER NOT NULL DEFAULT 0;
ALTER TABLE messages ADD COLUMN output_tokens INTEGER NOT NULL DEFAULT 0;
ALTER TABLE messages ADD COLUMN cost_usd NUMERIC(10, 6) NOT NULL DEFAULT 0;
ALTER TABLE messages ADD COLUMN model VARCHAR(50);
